KEYWORDS = [
    "India",
    "Australia",
    "England",
    "Pakistan",
    "South Africa",
    "West Indies",
    "New Zealand",
    "Sri Lanka",
    "Bangladesh",
    "Zimbabwe",
    "Afghanistan",
    "Syed Mushtaq",
    "Big Bash",
    "Pakistan Super",
    "Super Smash",
    "International League",
    "SA20",
    "Bangladesh Premier",
    "Idian Premier",
    "Vitality Blast",
    "Major Clubs",
    "Lanka Premier",
    "Caribbean Premier",
    "CSA T20",
    "National T20",
    "Shpageeza",
    "Major League",
    "Afghanistan Premier",
    "Abu Dhabi T20",
    "T20 World Cup",
]
